---
title: "Tidy 7 Eggs"
author: "Roshan"
date: "2023-04-15"
output: 
  html_document:
      toc: TRUE
      toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```




## Load libraries
```{r}

library(here)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(patchwork)
library(moveVis)
library(gganimate)

```


## Load data

```{r}

 tuesdata <- tidytuesdayR::tt_load('2023-04-11')

 eggproduction <- tuesdata$`egg-production`
 cagefreepercentages <- tuesdata$`cage-free-percentages`

#view(eggproduction)
#view(cagefreepercentages)

cleancages <- cagefreepercentages %>%   ### removing na and rounding percent columns
  na.omit() %>%
  mutate(percent_hens = round(percent_hens),
         percent_eggs = round(percent_eggs))
  
         # calling a function up to change colors
redtext <- function() {
  theme(plot.title = element_text(color = "red"),
        axis.text = element_text(color = "red"),
          axis.title = element_text(color = "red")) }
 

#view(cleancages)


g1 <- ggplot(cleancages,aes(x = observed_month, y = percent_hens))+
  geom_col(color = "blue", size = 12) +   ## really wanted a bar graph and tried but spent a while am gonna stick with the floating sticks
  geom_col(aes(x = observed_month, y = percent_eggs), color = "red", size = 12) + ## made them larger and more visible
transition_time(observed_month) +
  labs(title = "Month: {frame_time}") +
  #ggtitle("Increase of Percent hens vs percent eggs over 5 years")  this removed the timer :(
theme(axis.title = element_text(size = 20, face = "bold"),
        axis.text = element_text(size = 16))+
  ylab("PERCENT EGGS & HENS")+ ## Adding y-axis title reads easier in caps
  xlab("Observed years")+
  redtext() 

  
#ggsave(here("Output", "Tidy_7", "Tidy_7_eggs.png"))

animate(g1, fps = 30)  ## sped this up loads as was very slow at 3 
g1
```

